### ISSUE TITLE
3. Validate input with unfinished games and few players

### ISSUE THREAD

**Issue by WojtekMs** [Marcinati/testing#40]
Any ideas what might this mean?

**Comment by Tomonike** [comment]
It's about not full frames, e.g. `Name1:X|4-|3
Name2:34|X|0-`. A full game is 10 frames and it's about checking if the game is still in progress. 
```
### Lane 1: game in progress ###
Name1 30
Name2 44
34
### Lane 2: no game ###
### Lane 3: game finished ###
Michael 167
Radek 90
```
